#!/bin/sh

# For assistance call: 0793 572 8612
#              e-mail: fulford@citylinux.com
#             on-line: https://www.citylinux.com/belfield
#########################################################################
rcpt=fulford@citylinux.com
tmp=/tmp/chkcpu-$$
min=${1:-60}
idle=`sar 10 1 |awk 'END{print}'|awk '{print $5}'`
[ $idle -lt $min ] &&{
	sleep 5
	idle=`sar 10 1 |awk 'END{print}'|tee $tmp |awk '{print $5}'`
	[ $idle -lt $min ] &&{
		wio=`awk <$tmp '{print $4}'`
		/usr/lib/sendmail -C /etc/sendmail.cl $rcpt<<- .
			Subject: URGENT CPU costraint on BFL

			CPU at $idle% idle
			WIO at $wio%
		.
	}
}
rm $tmp
